### ISSUE TITLE
Multiselect issue: can't select items

### ISSUE THREAD

**Issue by avoinea** [eea/volto-metadata-block#23]
https://user-images.githubusercontent.com/323385/148253029-c8006040-d77c-4d0f-bb93-139e6edbb3e2.mp4

**Comment by nileshgulia1** [comment]
This behaviour isn't reproducible in FISE so far. I think it occurs for specific variation only (When there are nested columns inside)


https://user-images.githubusercontent.com/22280901/148516317-b771a3d4-17ae-4b92-a99c-1bf885479e55.mov

**Comment by nileshgulia1** [comment]
@avoinea Can you please give me access to https://alin.dev2aws.eea.europa.eu/ims/test-indicator
It's hard to test this locally.

**Comment by nileshgulia1** [comment]
Works in nested columns too. Needs further info.

https://user-images.githubusercontent.com/22280901/148520727-0f9638fd-e810-4968-b0fe-0caec53e13df.mov

**Comment by avoinea** [comment]
@nileshgulia1 Indeed the issue seems to be only when used metadata / metadata-section block within columns block
